---
- name: Developer
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: git,            tags: ['git'] }
    - { role: python,         tags: ['python'] }
    - { role: virtual_env,    tags: ['virtual_env'] }
    - { role: care_package,   tags: ['care_package'] }
    - { role: emacs,          tags: ['emacs'] }
    - { role: bennojoy.nginx, tags: ['nginx'] }
    